/**
    * code generated by JHelper
    * More info: https://github.com/AlexeyDmitriev/JHelper
    * @author Rick From Rickland
*/

#pragma GCC optimize("O2")

#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>

using namespace std;
using namespace __gnu_pbds;

typedef long long int ll;
typedef long double ld;
typedef pair<ll, ll> pll;
typedef pair<ld, ld> pld;
typedef pair<string, string> pss;
typedef pair<pll, ll> ppl;
typedef pair<ll, pll> plp;
typedef pair<pll, pll> ppp;

template<class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag, tree_order_statistics_node_update>;
//order_of_key , find_by_order
#define sz(x)                       (ll) x.size()
#define jjoin(x)                    for (auto i : x) cout << i << endl;
#define all(x)                      (x).begin(),(x).end()
#define F                           first
#define S                           second
#define Mp                          make_pair
#define sep                         ' '
#define error(x)                    cerr << #x << " = " << x << endl
#define fast_io                     ios::sync_with_stdio(false);cin.tie(0);cout.tie(0);
#define set_random                  mt19937_64 rng(chrono::steady_clock::now().time_since_epoch().count());
#define kill(x)                     return cout << x << endl , 0;
#define Hkill(x)                    cout << x << endl; exit(0);
#define endl                        '\n'

ll poww(ll a, ll b, ll md) {
    return (!b ? 1 : (b & 1 ? a * poww(a * a % md, b / 2, md) % md : poww(a * a % md, b / 2, md) % md));
}

const ll MAXN = 2e5 + 10;
const ll MAXA = 501;
const ll INF = 8e18;
const ll MOD = 998244353; //1e9 + 7
const ld PI = 4 * atan((ld) 1);

ll mark[MAXN], dist[MAXN], n, m, k;
vector<pll> adj[3][MAXN];

void Dijkstra() {
    memset(dist, 63, sizeof dist);
    dist[1] = 0;
    priority_queue<pll> pq;
    pq.push({0, 1});
    while (sz(pq)) {
        ll v = pq.top().S;
        pq.pop();
        if (mark[v]) continue;
        mark[v] = 1;
        for (pll nei : adj[1][v]) {
            ll u = nei.F, w = nei.S;
            if (dist[v] + w < dist[u]) {
                dist[u] = dist[v] + w;
                pq.push({-dist[u], u});
            }
        }
        for (pll nei : adj[2][v]) {
            ll u = nei.F, w = nei.S;
            if (dist[v] + w < dist[u]) {
                dist[u] = dist[v] + w;
                pq.push({-dist[u], u});
            }
        }
    }
    return;
}
int main() {
    fast_io;
    set_random;
    cin >> n >> m >> k;
    for (ll i = 1; i <= m; i++) {
        ll u, v, w;
        cin >> u >> v >> w;
        adj[1][u].emplace_back(v, w);
        adj[1][v].emplace_back(u ,w);
    }
    for (ll i = 1; i <= k; i++) {
        ll s, y;
        cin >> s >> y;
        adj[2][s].emplace_back(1, y);
        adj[2][1].emplace_back(s, y);
    }
    Dijkstra();
    ll cnt = k;
    for (ll v = 2; v <= n; v++) {
        bool f = 0;
        for (pll nei : adj[1][v]) {
            ll u = nei.F, w = nei.S;
            if (dist[v] == dist[u] + w) f = 1;
        }
        cnt -= !f;
    }
    cout << cnt << endl;
    return 0;
}
