/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Rick From Rickland
 */

#pragma GCC optimize("O2")

#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>

using namespace std;
using namespace __gnu_pbds;

typedef long long int ll;
typedef long double ld;
typedef pair<ll, ll> pll;
typedef pair<ld, ld> pld;
typedef pair<string, string> pss;
typedef pair<pll, ll> ppl;
typedef pair<ll, pll> plp;
typedef pair<pll, pll> ppp;

template<class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag, tree_order_statistics_node_update>;
//order_of_key , find_by_order
#define sz(x)                       (ll) x.size()
#define jjoin(x)                    for (auto i : x) cout << i << endl;
#define all(x)                      (x).begin(),(x).end()
#define F                           first
#define S                           second
#define Mp                          make_pair
#define sep                         ' '
#define error(x)                    cerr << #x << " = " << x << endl
#define fast_io                     ios::sync_with_stdio(false);cin.tie(0);cout.tie(0);
#define set_random                  mt19937_64 rng(chrono::steady_clock::now().time_since_epoch().count());
#define kill(x)                     return cout << x << endl , 0;
#define Hkill(x)                    cout << x << endl; exit(0);
#define endl                        '\n'

ll poww(ll a, ll b, ll md) {
    return (!b ? 1 : (b & 1 ? a * poww(a * a % md, b / 2, md) % md : poww(a * a % md, b / 2, md) % md));
}

const ll MAXN = 2e6 + 10;
const ll MAXA = 101;
const ll INF = 8e13;
const ll MOD = 998244353; //1e9 + 7
const ld PI = 4 * atan((ld) 1);
ll mark[MAXN], Edge[MAXN], W[MAXN], n, m;
vector<pll> adj[MAXN];

void bfs(ll v = -1, ll ind = -1) {
    memset(Edge, 63, sizeof Edge);
    queue<pll> Q;
    Q.emplace(1, 0);
    Edge[1] = 0;
    while (sz(Q)) {
        tie(v, ind) = Q.front();
        Q.pop();
        if (mark[v]) continue;
        mark[v] = 1;
        for (pll nei : adj[v]) {
            ll u = nei.F, w = nei.S;
            if (!Edge[u]) continue;
            if (!w) {
                Edge[u] = 0, Q.emplace(u, w);
            } else if (Edge[u] >= INF) {
                Edge[u] = w;
                Q.emplace(u, w);
            }
        }
    }
    return;
}

int main() {
    freopen("input.txt", "r", stdin);
    freopen("output.txt", "w", stdout);
    fast_io;
    set_random;
    cin >> n >> m;
    for (ll i = 1; i <= m; i++) {
        ll u, v;
        cin >> u >> v >> W[i];
        if (W[i]) {
            adj[u].emplace_back(v, i);
        } else adj[u].emplace_back(v, 0);
    }
    bfs();
    vector<ll> ans;
    for (ll i = 1; i <= n; i++) {
        if (Edge[i] >= INF) kill(-1);
        if (Edge[i]) ans.push_back(Edge[i]);
    }
    cout << sz(ans) << endl;
    for (ll x : ans)
        cout << x << sep;
    return 0;
}
