/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author parsa bahrami
 */

#pragma GCC optimize("O2")

#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>

using namespace std;
using namespace __gnu_pbds;

typedef long long int ll;
typedef long double ld;
typedef pair<ll, ll> pll;
typedef pair<ld, ld> pld;
typedef pair<string, string> pss;
typedef pair<pll, ll> ppl;
typedef pair<ll, pll> plp;
typedef pair<pll, pll> ppp;

template<class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag, tree_order_statistics_node_update>;
//order_of_key , find_by_order
#define sz(x)                       (ll) x.size()
#define jjoin(x)                    for (auto i : x) cout << i << endl;
#define all(x)                      (x).begin(),(x).end()
#define F                           first
#define S                           second
#define Mp                          make_pair
#define sep                         ' '
#define error(x)                    cerr << #x << " = " << x << endl
#define fast_io                     ios::sync_with_stdio(false);cin.tie(0);cout.tie(0);
#define set_random                  mt19937_64 rng(chrono::steady_clock::now().time_since_epoch().count());
#define kill(x)                     return cout << x << endl , 0;
#define Hkill(x)                    cout << x << endl; exit(0);
#define endl                        '\n'

ll poww(ll a, ll b, ll md) {
    return (!b ? 1 : (b & 1 ? a * poww(a * a % md, b / 2, md) % md : poww(a * a % md, b / 2, md) % md));
}

const ll MAXN = 2e6 + 10;
const ll MAXA = 101;
const ll INF = 8e18;
const ll MOD = 998244353; //1e9 + 7
const ld PI = 4 * atan((ld) 1);
vector<ll> adj[MAXN];
vector<pll> Edge;
ll mark[MAXN], dist[MAXN], Par[MAXN], n, k, d;
map<pll, ll> Rem;

void bfs() {
    memset(dist, 63, sizeof dist), memset(Par, -1, sizeof Par);
    queue<ll> Q;
    for (ll i = 1; i <= n; i++) {
        if (mark[i]) Q.push(i), dist[i] = 0;
    }
    while (sz(Q)) {
        ll v = Q.front();
        Q.pop();
        for (ll u : adj[v]) {
            if (dist[u] > dist[v] + 1) {
                dist[u] = dist[v] + 1;
                Par[u] = v;
                Q.push(u);
            }
        }
    }
    return;
}

int main() {
    fast_io;
    set_random;
    cin >> n >> k >> d;
    for (ll i = 1; i <= k; i++) {
        ll Ver;
        cin >> Ver;
        mark[Ver] = true;
    }
    for (ll i = 1; i <= n - 1; i++) {
        ll u, v;
        cin >> u >> v;
        Edge.emplace_back(u, v);
        adj[u].push_back(v), adj[v].push_back(u);
    }
    bfs();
    ll cnt = n - 1;
    for (ll i = 1; i <= n; i++) {
        if (dist[i] == 0) continue;
        Rem[{i, Par[i]}] = Rem[{Par[i], i}] = true;
        cnt--;
    }
    cout << cnt << endl;
    for (ll i = 0; i < n - 1; i++) {
        ll u = Edge[i].F, v = Edge[i].S;
        if (!Rem[{u, v}]) cout << i + 1 << sep;
    }
    return 0;
}
