/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Rick From Rickland
 */

#pragma GCC optimize("O2")

#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>

using namespace std;
using namespace __gnu_pbds;

typedef long long int ll;
typedef long double ld;
typedef pair<ll, ll> pll;
typedef pair<ld, ld> pld;
typedef pair<string, string> pss;
typedef pair<pll, ll> ppl;
typedef pair<ll, pll> plp;
typedef pair<pll, pll> ppp;

template<class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag, tree_order_statistics_node_update>;
//order_of_key , find_by_order
#define sz(x)                       (ll) x.size()
#define jjoin(x)                    for (auto i : x) cout << i << endl;
#define all(x)                      (x).begin(),(x).end()
#define F                           first
#define S                           second
#define Mp                          make_pair
#define sep                         ' '
#define error(x)                    cerr << #x << " = " << x << endl
#define fast_io                     ios::sync_with_stdio(false);cin.tie(0);cout.tie(0);
#define set_random                  mt19937_64 rng(chrono::steady_clock::now().time_since_epoch().count());
#define kill(x)                     return cout << x << endl , 0;
#define Hkill(x)                    cout << x << endl; exit(0);
#define endl                        '\n'

ll poww(ll a, ll b, ll md) {
    return (!b ? 1 : (b & 1 ? a * poww(a * a % md, b / 2, md) % md : poww(a * a % md, b / 2, md) % md));
}

const ll MAXN = 2e6 + 10;
const ll MAXA = 101;
const ll INF = 8e18;
const ll MOD = 998244353; //1e9 + 7
const ld PI = 4 * atan((ld) 1);

vector<pll> adj[MAXN];
ll dist[MAXN], Par[MAXN], n, m, sum = 0, Start;
map<pll, ll> idx, W;

void Dijkstra() {
    memset(dist, 63, sizeof dist);
    dist[Start] = 0;
    priority_queue<pll> pq;
    pq.push({0, Start});
    while (sz(pq)) {
        ll v = pq.top().S;
        pq.pop();
        for (pll nei : adj[v]) {
            ll u = nei.F, w = nei.S;
            if (dist[v] + w < dist[u]) {
                dist[u] = dist[v] + w;
                Par[u] = v;
                pq.push({-dist[u], u});
            } else if (dist[v] + w == dist[u] && W[{Par[u], u}] > w) Par[u] = v;
        }
    }
    return;
}

int main() {
    fast_io;
    set_random;
    cin >> n >> m;
    for (ll i = 1; i <= m; i++) {
        ll u, v, w;
        cin >> u >> v >> w;
        adj[u].emplace_back(v, w), adj[v].emplace_back(u, w);
        idx[{u, v}] = idx[{v, u}] = i;
        W[{u, v}] = W[{v, u}] = w;
    }
    cin >> Start;
    Dijkstra();
    for (ll i = 1; i <= n; i++) sum += W[{i, Par[i]}];
    cout << sum << endl;
    for (ll i = 1; i <= n; i++) {
        if (Par[i] == 0) continue;
        cout << idx[{i, Par[i]}] << sep;
    }
    cout << endl;
    return 0;
}
